version: '3'

services:
  backend:
    build:
      context: ${BACK_DIR_PATH}/
    ports:
      - "8000:8000"
    volumes:
      - ${BACK_DIR_PATH}:/app
    depends_on:
      - db
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}

  frontend:
    build:
      context: ${FRONT_DIR_PATH}/
    ports:
      - "3000:80"
    volumes:
      - ${FRONT_DIR_PATH}:/app

  db:
    image: postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
     - "5433:5432"
