# Generated by Django 5.0.2 on 2024-03-03 22:10

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import employees.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("files", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScientificWork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=512, verbose_name="Назва наукової роботи"
                    ),
                ),
                (
                    "publishing_house",
                    models.CharField(max_length=512, verbose_name="Видавництво"),
                ),
                (
                    "size",
                    models.PositiveSmallIntegerField(verbose_name="Кількість сторінок"),
                ),
                (
                    "language",
                    models.CharField(
                        default="українська", max_length=100, verbose_name="Мова"
                    ),
                ),
                (
                    "isbn",
                    models.CharField(
                        max_length=17,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_format",
                                message="ISBN повинен мати формат XXX-XXX-XXX-XXX-X",
                                regex="^\\d{3}-\\d{3}-\\d{3}-\\d{3}-\\d$",
                            )
                        ],
                        verbose_name="ISBN",
                    ),
                ),
                (
                    "coworkers",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        default=list,
                        size=None,
                        verbose_name="Автори роботи(інші)",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, max_length=5000, verbose_name="Опис наукової роботи"
                    ),
                ),
            ],
            options={
                "verbose_name": "Наукова робота",
                "verbose_name_plural": "Наукові роботи",
            },
        ),
        migrations.CreateModel(
            name="ScientificWorkType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="Підручники",
                        max_length=255,
                        verbose_name="Назва типу наукових робіт",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True, max_length=255, verbose_name="Слаг"
                    ),
                ),
            ],
            options={
                "verbose_name": "Тип наукової роботи",
                "verbose_name_plural": "Типи наукових робіт",
            },
        ),
        migrations.CreateModel(
            name="TeachDiscipline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, verbose_name="Назва наукової дисципліни"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        max_length=5000,
                        verbose_name="Опис наукової дисципліни",
                    ),
                ),
                (
                    "time_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Час і дата створення"
                    ),
                ),
                (
                    "time_last_modified",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Час і дата останньої зміни"
                    ),
                ),
            ],
            options={
                "verbose_name": "Навчальна дисципліна",
                "verbose_name_plural": "Навчальні дисципліни",
                "ordering": ("-time_created",),
                "get_latest_by": "time_created",
            },
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="Прізвище"),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Ім'я")),
                (
                    "middle_name",
                    models.CharField(max_length=100, verbose_name="По батькові"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Адреса електронної пошти",
                    ),
                ),
                (
                    "ranks",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        default=list,
                        size=None,
                        verbose_name="Наукові ступені",
                    ),
                ),
                (
                    "links",
                    models.JSONField(
                        default=employees.models.links_default, verbose_name="Посилання"
                    ),
                ),
                ("degree_history", models.TextField(verbose_name="Освіта та кар'єра")),
                (
                    "study_interests",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        default=list,
                        size=None,
                        verbose_name="Сфера наукових інтересів",
                    ),
                ),
                (
                    "diploma_work_topics",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        default=list,
                        size=None,
                        verbose_name="Теми курсових та дипломних робіт",
                    ),
                ),
                (
                    "awards",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=512),
                        blank=True,
                        default=list,
                        size=None,
                        verbose_name="Академічні нагороди та премії",
                    ),
                ),
                (
                    "chosen_publications",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=512),
                        blank=True,
                        default=list,
                        size=None,
                        verbose_name="Вибрані публікації",
                    ),
                ),
                (
                    "time_created",
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name="Час створення сторінки співробітника",
                    ),
                ),
                (
                    "time_last_modified",
                    models.DateTimeField(
                        auto_now=True,
                        verbose_name="Час останньої зміни сторінки співробітника",
                    ),
                ),
                ("slug", models.SlugField(max_length=300, verbose_name="Слаг")),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="image_employees",
                        related_query_name="image_employee",
                        to="files.file",
                        verbose_name="Зображення",
                    ),
                ),
            ],
            options={
                "verbose_name": "Співробітник кафедри",
                "verbose_name_plural": "Співробітники кафедри",
                "ordering": ("-time_created",),
                "get_latest_by": "time_created",
            },
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, verbose_name="Назва наукового звання"
                    ),
                ),
            ],
            options={
                "verbose_name": "Наукове звання",
                "verbose_name_plural": "Наукові звання",
                "indexes": [models.Index(fields=["name"], name="name_index")],
            },
        ),
        migrations.AddConstraint(
            model_name="position",
            constraint=models.UniqueConstraint(
                fields=("name",), name="name_unique_constraint"
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="position",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="position_employees",
                related_query_name="position_employee",
                to="employees.position",
                verbose_name="Наукове звання",
            ),
        ),
        migrations.AddField(
            model_name="scientificwork",
            name="file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="files_scientific_works",
                related_query_name="file_scientific_work",
                to="files.file",
                verbose_name="Файловий зміст",
            ),
        ),
        migrations.AddField(
            model_name="scientificwork",
            name="image",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="image_scientific_work",
                related_query_name="image_scientific_work",
                to="files.file",
                verbose_name="Зображення(титульна сторінка)",
            ),
        ),
        migrations.AddField(
            model_name="scientificwork",
            name="workers",
            field=models.ManyToManyField(
                related_name="scientific_works",
                related_query_name="scientific_work",
                to="employees.employee",
                verbose_name="Автори роботи(Співробітники кафедри)",
            ),
        ),
        migrations.AddIndex(
            model_name="scientificworktype",
            index=models.Index(fields=["name"], name="worktype_name_index"),
        ),
        migrations.AddIndex(
            model_name="scientificworktype",
            index=models.Index(fields=["slug"], name="worktype_slug_index"),
        ),
        migrations.AddConstraint(
            model_name="scientificworktype",
            constraint=models.UniqueConstraint(
                fields=("name",), name="worktype_name_unique_constraint"
            ),
        ),
        migrations.AddConstraint(
            model_name="scientificworktype",
            constraint=models.UniqueConstraint(
                fields=("slug",), name="worktype_slug_unique_constraint"
            ),
        ),
        migrations.AddField(
            model_name="scientificwork",
            name="type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="scientific_works",
                related_query_name="scientific_work",
                to="employees.scientificworktype",
                verbose_name="Тип наукової роботи",
            ),
        ),
        migrations.AddIndex(
            model_name="teachdiscipline",
            index=models.Index(fields=["name"], name="discipline_name_index"),
        ),
        migrations.AddConstraint(
            model_name="teachdiscipline",
            constraint=models.UniqueConstraint(
                fields=("name",), name="discipline_name_unique_constraint"
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="teach_disciplines",
            field=models.ManyToManyField(
                related_name="discipline_employees",
                related_query_name="discipline_employee",
                to="employees.teachdiscipline",
                verbose_name="Викладацька діяльність",
            ),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(fields=["slug"], name="employee_slug_index"),
        ),
        migrations.AddConstraint(
            model_name="employee",
            constraint=models.UniqueConstraint(
                fields=("first_name", "last_name", "middle_name"),
                name="employee_fullname_unique_constraint",
            ),
        ),
        migrations.AddConstraint(
            model_name="employee",
            constraint=models.UniqueConstraint(
                fields=("email",), name="employee_email_unique_constraint"
            ),
        ),
        migrations.AddConstraint(
            model_name="employee",
            constraint=models.UniqueConstraint(
                fields=("slug",), name="employee_slug_unique_constraint"
            ),
        ),
    ]
