# Generated by Django 5.0.2 on 2024-03-03 22:56

import employees.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="scientificworktype",
            options={
                "verbose_name": "Тип наукових робіт",
                "verbose_name_plural": "Типи наукових робіт",
            },
        ),
        migrations.AlterField(
            model_name="employee",
            name="links",
            field=models.JSONField(
                blank=True,
                default=employees.models.links_default,
                verbose_name="Посилання",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="slug",
            field=models.SlugField(
                allow_unicode=True, max_length=300, verbose_name="Слаг"
            ),
        ),
        migrations.AlterField(
            model_name="scientificwork",
            name="description",
            field=models.TextField(
                blank=True, max_length=10000, verbose_name="Опис наукової роботи"
            ),
        ),
        migrations.AlterField(
            model_name="scientificwork",
            name="workers",
            field=models.ManyToManyField(
                blank=True,
                related_name="scientific_works",
                related_query_name="scientific_work",
                to="employees.employee",
                verbose_name="Автори роботи(Співробітники кафедри)",
            ),
        ),
    ]
