# Generated by Django 5.0.2 on 2024-04-16 16:15

import employees.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0003_alter_employee_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="awards",
            field=employees.models.CustomArrayField(
                base_field=models.CharField(max_length=512),
                blank=True,
                default=list,
                size=None,
                verbose_name="Академічні нагороди та премії",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="chosen_publications",
            field=employees.models.CustomArrayField(
                base_field=models.CharField(max_length=512),
                blank=True,
                default=list,
                size=None,
                verbose_name="Вибрані публікації",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="diploma_work_topics",
            field=employees.models.CustomArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                default=list,
                size=None,
                verbose_name="Теми курсових та дипломних робіт",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="ranks",
            field=employees.models.CustomArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                default=list,
                size=None,
                verbose_name="Наукові ступені",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="study_interests",
            field=employees.models.CustomArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                default=list,
                size=None,
                verbose_name="Сфера наукових інтересів",
            ),
        ),
        migrations.AlterField(
            model_name="scientificwork",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="scientific_work_files",
                verbose_name="Вміст наукової роботи",
            ),
        ),
        migrations.AlterField(
            model_name="scientificwork",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="scientific_work_images",
                verbose_name="Обкладинка наукової роботи",
            ),
        ),
    ]
