# Generated by Django 5.0.2 on 2024-04-16 16:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0004_alter_employee_awards_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="teach_disciplines",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="discipline_employees",
                related_query_name="discipline_employee",
                to="employees.teachdiscipline",
                verbose_name="Викладацька діяльність",
            ),
        ),
    ]
