# Generated by Django 5.0.4 on 2024-04-29 18:33

import employees.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0005_alter_employee_teach_disciplines"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="awards",
            field=employees.models.CustomArrayField(
                base_field=models.CharField(max_length=1024),
                blank=True,
                default=list,
                size=None,
                verbose_name="Академічні нагороди та премії",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="chosen_publications",
            field=employees.models.CustomArrayField(
                base_field=models.CharField(max_length=1024),
                blank=True,
                default=list,
                size=None,
                verbose_name="Вибрані публікації",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="diploma_work_topics",
            field=employees.models.CustomArrayField(
                base_field=models.CharField(max_length=1024),
                blank=True,
                default=list,
                size=None,
                verbose_name="Теми курсових та дипломних робіт",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="study_interests",
            field=employees.models.CustomArrayField(
                base_field=models.CharField(max_length=1024),
                blank=True,
                default=list,
                size=None,
                verbose_name="Сфера наукових інтересів",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="teach_disciplines",
            field=models.ManyToManyField(
                blank=True,
                related_name="discipline_employees",
                related_query_name="discipline_employee",
                to="employees.teachdiscipline",
                verbose_name="Викладацька діяльність",
            ),
        ),
    ]
