# Generated by Django 5.0.4 on 2024-05-01 14:30

import employees.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_alter_employee_awards_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='ranks',
            field=employees.models.CustomArrayField(base_field=models.CharField(max_length=1024), blank=True, default=list, size=None, verbose_name='Наукові ступені'),
        ),
    ]
