# Generated by Django 5.0.4 on 2024-05-01 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_alter_employee_ranks'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='teachdiscipline',
            name='discipline_name_unique_constraint',
        ),
    ]
