# Generated by Django 5.0.4 on 2024-05-20 12:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0009_alter_employee_awards_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="image",
            field=models.ImageField(
                blank=True,
                default="employee_images/default_avatar.jpg",
                upload_to="employee_images/",
                verbose_name="Фото",
            ),
        ),
    ]
