# Generated by Django 5.0.4 on 2024-05-20 12:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0010_alter_employee_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scientificwork",
            name="type",
        ),
        migrations.RemoveField(
            model_name="scientificwork",
            name="workers",
        ),
        migrations.DeleteModel(
            name="ScientificWorkType",
        ),
        migrations.DeleteModel(
            name="ScientificWork",
        ),
    ]
