# Generated by Django 5.0.6 on 2024-05-21 11:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0012_alter_employee_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="awards",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(max_length=1024),
                blank=True,
                default=list,
                size=None,
                verbose_name="Академічні нагороди та премії",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="chosen_publications",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(max_length=1024),
                blank=True,
                default=list,
                size=None,
                verbose_name="Вибрані публікації",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="diploma_work_topics",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=1024),
                blank=True,
                default=list,
                size=None,
                verbose_name="Теми курсових та дипломних робіт",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="ranks",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(max_length=1024),
                blank=True,
                default=list,
                size=None,
                verbose_name="Наукові ступені",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="study_interests",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(max_length=1024),
                blank=True,
                default=list,
                size=None,
                verbose_name="Сфера наукових інтересів",
            ),
        ),
    ]
