# Generated by Django 5.0.6 on 2024-05-23 12:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0015_alter_employee_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
