# Generated by Django 5.0.6 on 2024-05-23 14:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0016_employee_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="is_active",
            field=models.BooleanField(
                default=True, verbose_name="Чи є нинішнім співробітником"
            ),
        ),
    ]
