# Generated by Django 5.0.4 on 2024-04-29 18:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("educational_degrees", "0002_alter_educationaldegree_detailed_info_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="educationaldegree",
            options={
                "verbose_name": "Освітній ступінь",
                "verbose_name_plural": "Освітні ступені",
            },
        ),
    ]
