# Generated by Django 5.0.6 on 2024-05-23 09:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "educational_degrees",
            "0006_alter_subject_options_alter_subjectblock_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="qualificationwork",
            name="topic_of_work",
            field=models.CharField(
                blank=True, verbose_name="Тема кваліфікаційної роботи"
            ),
        ),
    ]
