# Generated by Django 5.0.6 on 2024-05-23 12:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("educational_degrees", "0007_alter_qualificationwork_topic_of_work"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="qualificationwork",
            options={
                "ordering": ("full_name",),
                "verbose_name": "Кваліфікаційна робота",
                "verbose_name_plural": "Кваліфікаційні роботи",
            },
        ),
    ]
