# Generated by Django 5.0.6 on 2024-05-24 11:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "educational_degrees",
            "0009_remove_educationaldegree_study_programs_desc_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="EducationalDegreeStudyProgramsFiles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="educational_degrees_files/", verbose_name="Файл"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Назва файла")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Файл освітньої програми",
                "verbose_name_plural": "Файли освітніх програм",
            },
        ),
        migrations.AlterModelOptions(
            name="educationaldegreedetailsfiles",
            options={
                "verbose_name": "Файл опису наукового ступіня",
                "verbose_name_plural": "Файли опису наукового ступіня",
            },
        ),
        migrations.AlterField(
            model_name="educationaldegree",
            name="detailed_info",
            field=models.ManyToManyField(
                blank=True,
                related_name="detailed_info_files",
                related_query_name="detailed_info_file",
                to="educational_degrees.educationaldegreedetailsfiles",
                verbose_name="Описи освітнього ступіня",
            ),
        ),
        migrations.AddField(
            model_name="educationaldegree",
            name="study_programs_desc",
            field=models.ManyToManyField(
                blank=True,
                related_name="study_programs",
                related_query_name="study_program",
                to="educational_degrees.educationaldegreestudyprogramsfiles",
                verbose_name="Описи освітньої програми",
            ),
        ),
    ]
